Repository MyIceCreamBox/IceCreamBox-Front, pull requests merged in 2023-06, with the labels that each got.

#17 feat: login-로그인 API 연결
  MyIceCreamBox_Front/package-lock.json
  MyIceCreamBox_Front/package.json
  MyIceCreamBox_Front/src/login/login.js
Labels: 💻Feature

#27 fix:login-token 저장
  MyIceCreamBox_Front/src/login/login.js
Labels: 🛠️Fix

#31 Feat:회원가입 아이디 이메일 변환
  MyIceCreamBox_Front/package-lock.json
  MyIceCreamBox_Front/package.json
  MyIceCreamBox_Front/src/loggedInMainpage/buttons/iceCheckButton.js
  MyIceCreamBox_Front/src/login/doubleCheck_btn.js
  MyIceCreamBox_Front/src/login/input.js
  MyIceCreamBox_Front/src/login/login.js
  MyIceCreamBox_Front/src/login/signup.js
Labels: 💻Feature

#34 feat:etc-404 마이페이지&링크공유&선물보내기&받은 선물 확인&보낼 기회 확인&선물 비율 확인 404 페이지 연결
  MyIceCreamBox_Front/src/loggedInMainpage/buttons/sendButton.js
  MyIceCreamBox_Front/src/loggedInMainpage/loggedInMainpage.js
  MyIceCreamBox_Front/src/loggedInMainpage/main/ellipse.js
  MyIceCreamBox_Front/src/mainpage/movemain_btn.js
  MyIceCreamBox_Front/src/mypage/header/nickname.js
  MyIceCreamBox_Front/src/mypage/header/piechart.js
  MyIceCreamBox_Front/src/sendpage/screens/ConfigLetterScreen.js
Labels: 💻Feature

#37 feat:로그인->메인페이지 loading 페이지 연결
  MyIceCreamBox_Front/src/loggedInMainpage/loggedInMainpage.js
Labels: 💻Feature

#39 refactor:프로젝트 시작 메인페이지로 변경
  MyIceCreamBox_Front/src/login/signup.js
  MyIceCreamBox_Front/src/stack.js
Labels: 🛠️Refactor

#40 refactor: mypage 코드 리팩토링
  MyIceCreamBox_Front/src/mypage/content/bBar.js
  MyIceCreamBox_Front/src/mypage/content/cBar.js
  MyIceCreamBox_Front/src/mypage/content/cpdBar.js
  MyIceCreamBox_Front/src/mypage/content/ctdBar.js
  MyIceCreamBox_Front/src/mypage/content/friendMessage.js
  MyIceCreamBox_Front/src/mypage/content/iceList.js
  MyIceCreamBox_Front/src/mypage/content/mbaCon.js
  MyIceCreamBox_Front/src/mypage/content/oBar.js
  MyIceCreamBox_Front/src/mypage/content/pBar.js
  MyIceCreamBox_Front/src/mypage/content/soCon.js
  MyIceCreamBox_Front/src/mypage/content/strawberry.js
Labels: 🛠️Refactor
